### ISSUE TITLE
The Agent must implement the spec

### ISSUE THREAD

**Issue by SGrondin** [Mashape/galileo-agent-java#4]
Make sure that the agent implements every detail in the spec, including the HTTP flush times, ZMQ flush events, etc.

https://github.com/Mashape/analytics-agent-spec/blob/master/README.md

**Comment by shashiranjan84** [comment]
Currently Java agent starts a thread pool and each thread owns a zmq socket. All ALF(one ALF has only one HAR) is queued on a blocking queue list and Executor assign one ALF to a thread to send it to analytics server. if a thread is idle for for more than 5 second, it is destroyed along with the socket. In case any exception thrown by zmq lib while sending ALF, thread create new socket connection and try again to send data (3 times). So basically agent does not care how ZMQ eventually send the data. 

Given that its difficult for me

The agent MUST:
- [x] Connect to tcp://socket.analytics.mashape.com:5500 in PUSH mode
- [x] Send ALFs automatically on the socket as they arrive

- [ ] Listen to the flush event. If an ALF cannot be flushed within 5 seconds, then the ALF is put in a array/list called 'buffer'. Every ALF needs its own individual timeout 5-second timeout.

- [ ] Set a background timer/interval that executes a function every 5 seconds. That function checks the buffer length. If it's greater than 0, the ZMQ socket is destroyed and replaced with a new one. Then the buffer is emptied into the new socket. Don't forget that every ALF still needs its own 5-second timeout to check if it has been flushed successfully.

Not sure about above two requirements, Java Agent got its own buffering thing to handle load. Also not sure about ZMQ Java implementation providing any listener   

- [ ] Every 5 minutes, replace the socket with a fresh one (to give the ELB a chance to distribute load around).

Agent destroy the connection if thread is idle for more than 5 seconds. But if there is active it will keep using same socket

**Comment by SGrondin** [comment]
It seems like you're filling all the requirements. Basically if the ALF can't be sent you will be trying again on another socket. JeroMQ is a different implementation, so it's normal that your approach differs. :+1:

**Comment by ahmadnassri** [comment]
re-opning since that checklist is not done?

**Comment by shashiranjan84** [comment]
As mentioned earlier Agent handles buffering and refreshing of socket connection in its own way. I will check my code and will try to fit in all the thresholds along with name change in next release

**Comment by ahmadnassri** [comment]
as per recent conversation, agents need to switch to HTTP.

**Comment by shashiranjan84** [comment]
Working on it, will also try to incorporate all the checkpoints from the spec.
