### ISSUE TITLE
Not getting header or response content in a static jsp

### ISSUE THREAD

**Issue by kennethklee** [Mashape/galileo-agent-java#5]
Getting zero headers and empty response in Galileo. And server actually responds with blank when it should have served the static jsp.

Using:
* Tomcat 8.0.30
* Java 1.7
* IDE is Eclipse Mars (in case that is relevant for maven versions)

Here's index.jsp:
```jsp
<html>
<body>
<h2>Hello World!</h2>
</body>
</html>
```

Reproduction steps:

1. Create maven archetype, webapp (creates 3 files: `pom.xml`, `web.xml`, and `index.jsp` and a bunch of folders)
2. Add analytics dependencies to `pom.xml`
3. Add analytics params to `web.xml`
4. Add enable, serviceToken and environment to server vm args

Expected:

Server should have responded with "Hello World!". Galileo should have captured the content, and the headers.

Actual:
**Server response**
![image](https://cloud.githubusercontent.com/assets/838810/11660558/b0a93e74-9d9b-11e5-9026-65b140c23b21.png)

**Galileo**
![image](https://cloud.githubusercontent.com/assets/838810/11660566/b97a5830-9d9b-11e5-94e5-26ecbf3a51b4.png)

Notes:
Looks like the filter isn't getting the cloned response output stream.

**Comment by kennethklee** [comment]
Upon further investigation:

This doesn't work:
```java
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter()
			.write("<h1>Hello World!</h1>");			
	}
```

While this does:
```java
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getOutputStream()
			.println("<h1>Hello World!</h1>");			
	}
```

**Comment by shashiranjan84** [comment]
Fixed.
